test: &default

  # Credentials for REST APIs
  client_id: AR3evNGzgPmK14pWZ0ODRHRdWYVULo4SURypBX5uQ8lIfTp6VRzKJQizmgxRU-BWIuiXFlTkM09UlQK3
  client_secret: EIJ_tqFbrenkZFfd3xK8h81iQgqri1MI0UeYQHejrpgSXxGTz3rurzs7fg87IrgmP3ZWPJ0btW7briM0
  # Mode can be 'live' or 'sandbox'
  mode: sandbox
  ssl_options:
    ca_file: null
 
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: a20160383@utem.edu.mx


  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default
  #mode: live

production:
  <<: *default
  mode: live
