test: &default

  # Credentials for REST APIs
  client_id: AXB-2XXlsI5_BoPJvCNNeIQi9hqMQm186Q_RiVz8Ed0GJ7Yc3b5I8E6HTA_zD9l2XU5KnIxXa4BxjdmL
  client_secret: EO422dn3gQLgDbuwqTjzrFgFtaRLRR5BdHEESmha49TMEMShMhekhbGijuR-du8mzBIH3fM0RQWzHDcEn-sIkjGkYvQeKYHi62gOaYePZpqoarz6PghZIxLwVRkp

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: sb-ekhby5095784@business.example.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
